### ISSUE TITLE
Entity Specific Values in Content

### ISSUE THREAD

**Issue by markhayden** [lytics/pathforajs#137]
We already have the ability through Lytics to pass a white listed field to pathfora (e.g. email address). There is, however, no simple way to get a dynamic value into the body or title of a pathfora widget. For instance, a promo code for a specific set of users. 

Lets explore a simple template solution, similar to handlebars perhaps, that allows for basic string replacement on a pathfora widget. We need to take care to think of how to handle default values or possibly even formatting here as well. 

example:

```
Use promo code: {{user_promo | DEFAULTPROMO}} today!
```

where defaultpromo is the default string. likewise, we could always take the approach of "if there is no key for that user throw it out" and prevent the modal from being loaded for anyone that doesn't meed the full specs?

**Comment by markhayden** [comment]
ref https://github.com/lytics/customerprojects/issues/11

**Comment by sarahyablok** [comment]
As I am beginning to work on this, supporting simple value replacements is each enough:

```
headline: 'Welcome {{name | Valued Customer}}!',
```
(where "Valued Customer" is the default, should the name value not exist).
And there's the possibility of doing more complex if/else statements:

```
msg: 'Thanks for {% if visitct == 0 %}visiting for the first time{% else %}returning{% end %}'
```

I almost don't think these conditionals are necessary, since today we could build two separate campaigns with separate messages, and have the logic be in the segmentation. I could see some argument for it being supported in the future if we have people juggling many dynamic campaigns, but as for now I don't think it makes sense to implement something that deep. @markhayden

**Comment by sarahyablok** [comment]
I also see a couple use cases for the case of what to do if the field doesn't exist.

1. Use the fallback provided after the `|` character
2. If no fallback is provided, replace the template with an empty string
3. If no fallback is provided, don't show the widget.

I think option 1 & 2 should be the default settings, and then I will add a new `displayCondition` for option 3:

```
displayConditions: {
   hideOnMissingField: true
}
```

or something of that nature? feel free to comment with suggestions.

**Comment by markhayden** [comment]
i would say 3 should be default behavior. we want to protect customers against bad experiences and they wont always be able to know / control when data is available for any given user. so i'd say if no data and no fallback = dont show widget. then if u want the blank behavior its a manual override 

e.g. showOnMissingFields
