### ISSUE TITLE
Incorrect input style for "message" field

### ISSUE THREAD

**Issue by bpatterson88** [lytics/pathforajs#163]
The message `<input>` doesn't match the rest of the inputs. 

<img width="844" alt="screen shot 2016-12-22 at 4 56 12 pm" src="https://cloud.githubusercontent.com/assets/15875886/21444903/9e9e768e-c867-11e6-8246-a3aac3d665b7.png">

**Comment by sarahyablok** [comment]
This looks like a demo from our marketing site? I can tell because the input styles you're seeing were added to the marketing site for a previous campaign which only had input fields, so I didn't bother to add styles for `<textarea>` The input boxes in pathfora should all normally look the same as the message textarea you're seeing. If you'd like me to add the same styles to it on the marketing site for demo purposes, feel free to open a ticket over there, or just ask me over slack. :)
