### ISSUE TITLE
Content Recommendations: Idea Drafting

### ISSUE THREAD

**Issue by sarahyablok** [lytics/pathforajs#81]
In the near future we'd like to offer content recommendations from our content recommendation API as a feature in PathforaJS. This ticket should present a couple ideas/question of how we'd like to handle the config and options.

**1.**
 Should we make recommendations only at a segment level or should we also include user-level recommendations? What about both?

```javascript
recommend: {
  level: "user", // segment would automatically match the one in the target of the config
}
```

**2.**
 Should we allow the user to define the filter fully? Or we could define pre-made filters to encompass things like url matching and topic relevance? The pros of having predefined options is that there will be less user error, and it'll translate better into the personalization UI.

(full definition) example
```javascript
recommend: {
  filter: "FILTER AND (url LIKE 'www.getlytics.com/integrations/*') FROM content",
}
```

(pre-defined) example
```javascript
recommend: {
  filter: {
    operator: "or",
    url: "www.getlytics.com/integrations/*"
    topics: ["marketing", "data"],
  }
}
// Equivalent to FILTER OR (url LIKE www.getlytics.com/integrations/*', global.marketing > 0, global.data > 0) FROM content
```

**3.**
Users might want to only display content that the user hasn't seen before, we can use the `visited` field in the API for this.

```javascript
recommend: {
  showVisited: false, // default is true
}
```

**4.**
Users will want to be able to define default text/headline to display for recommended articles. We could autofill with the title and description, but chances are people will want to define this. We could make the title or other fields of the document available to them while setting this description though!

```javascript
// Defined outside of the recommend as the default headline/msg
headline: "Welcome",
msg: "Based on your interests we think you'll enjoy this: {{title}}", // Where {{title}} is replaced with the name of the doc
```

**5.**
There should be a default option text option, if for some reason the api does not return any documents for that visitor we should allow the user to set a default piece of content to recommend.

```javascript
recommend: {
	default: {
		headline: "Welcome",
		msg: "We think you'll enjoy this: Using Data Visualization to Enhance the Narrative",
		url: "https://www.getlytics.com/blog/post/data_vis_enhances_narrative",
		img: "https://www.getlytics.com/img/blog/posts/data_vis_enhances_narrative/data_vis_enhances_narrative-bg.gif"	
	}
}
```

Comments and more ideas are welcome. We want to come up with a clear goal/plan for v1.

**Comment by markhayden** [comment]
still reading through but one thing we had also talked about was creating a new variation for content promotion. sort of like facebook or twitter where they format the page data (image, headline, description) and then let you add a headline/body on top of that. 

![image](https://cloud.githubusercontent.com/assets/2042008/15232513/afd3600c-1856-11e6-97fb-891f54de6346.png)

so probably dont need the ability to edit title / description in the first iteration.

**Comment by markhayden** [comment]
> 1. segment or user or both

both

> 2. i would say in the first version lets just do the raw filter. we'll likely build on this but it would be good 

to get it out into the world and see how it works how that ql evolves before requiring a translation service on the pathfora end.

> 3. dont reco same content

need to ponder this one. seems like a service level thing. maybe the api needs the ability to exclude or something like that but you are definitely right. i may or may not want to push the same content over and over.

> 4. previous message

IF we allow for content editing i think this would need to happen in the ui. we wont know the recommendation until its returned in real time so it seems pretty challenging to allow users to alter the content returned. seems to be better handled like facebook. where u update the site and then hit an update button which triggers a re-scrape on the facebook side.

> 5. default

definitely agree.

one thing to thing about is the content (default for instance) probably should live outside of the recommend objects. keep that for settings level stuff and then figure out how we'd want to add in additional content on top of the existing msg / body. probably `supporting_content` or something more cleverly named than that.

**Comment by sarahyablok** [comment]
@markhayden Thanks! 

RE msg/headline: I agree, perhaps the custom messaging is too ambitious for v1. One this to be aware of too, currently the content API returns descriptions in all lowercase, which is not the nicest thing to read/the most professional looking. I'm not sure exactly what the reason for this is, and it may be a quick fix. I can check with data science. But if we can just do with the description I agree we should for v1.

RE previously visited content: Yeah, I was hoping the filter would allow us to do something like `FILTER AND (NOT visited)` or something similar, but it does not currently. Again this is something I can ask data science.

**Comment by araddon** [comment]
* Should we split out and make a new "Content Collection" the only way to do content filtering?  Where that is separate api?   Not as simple/straight-forward but at same time grouping both content-select-filtering as well as how to display type functionality sounds complicated?
* do we need some type of random-ness (ie, make sure if same user views same list multiple times it maybe varies content each time?   kind of like ad servers)?
* what is simplest version for now?   ie, I think just recommendation with no other features would be valuable.    so maybe immediately identify v1 vs v2?  I think a lot of the variation stuff, templating, show-visited, randomness should not be in v1

**Comment by araddon** [comment]
@drewlanenga does it even make sense to make recommendations at segment level?   Is that supported in api, or is user-level all we have?

**Comment by sarahyablok** [comment]
@araddon I agree! Once all the ideas have been hashed out I will probably close this issue and split it up into two - v1 and v2/future.

Also are you suggesting we make a new pathfora type instead of just using `Message`? Something like:

```javascript
var rec = new pathfora.ContentRecommend({
   // fields and such here
});
```
I initially was thinking we could just make `recommend` an optional field on a `Message`, but I do like the idea above.

**Comment by markhayden** [comment]
yah i dont think we want a new type, it would be a variation of the existing 4 or so types. promoting content drops in the standard img, title, meta template to the existing widgets.

**Comment by araddon** [comment]
Yes, i wonder if its more like:

```javascript

// Normal pathfora
var promoWidget = new pathfora.Message({
    layout: "modal",
    msg: "Welcome to our website"
});


// Content Recommendation
var promoWidget = new pathfora.Message({
    layout: "modal",
    msg: {
       content:  "recommendation",
       contentFilter: "*"
    }
});



```

**Comment by markhayden** [comment]
i was thinking something along the lines of:

```
var promoWidget = new pathfora.Message({
  "layout": "modal",
  "variation": 3,
  "msg": "some cool content we know you'll be interested in",
  "ref": [
    {
      "title": "My Page Title",
      "descr": "My page meta description",
      "img": "http://mypageimage.com/woot.jpg",
    }
  ]
});```

where variation 3 tells pathfora it needs to add the site template and the ref contains recommended content. the reason i think something generic like ref is better is flexibility. for this, it would be recommendations (1 or more) then pathfora can determine what to do with those recommendations. down the road there may be some other type of enrichment we support, this would allow it to also live there perhaps. 

likewise i am pretty confident users will still want to add the context of why i am getting the modal which is why the headline and msg continues to exist. if you dont use it, its hidden but that way we are not handling those fields special for specific widgets. just less prone to break?

i dont care what we call `ref` could be `data`, `children`, `support`, `meta`, etc. just a bucket of supporting content.

**Comment by araddon** [comment]
Im not sure i want to merge/conflate/combine what i see as 2 concepts:
* content-recommendation:  predictive selection of content from large(ish) list of possible content items.   
* content-optimization:   presentation of multiple variations of same content-unit to see which is better.

Im not saying we would never go to allow both, but just want to separate the two for the first go around.  Just too many concepts for first release.   

Also, long term i would like to build the variations into the content-unit layer NOT the campaign layer.  ie, all content units have multiple variations and we are constantly optimizing them.  not on a per-campaign basis.   

* *content-unit*:   singular in nature for single general piece of content, has n title/images available for optimization.  1:n to content groups, campaign-message ie same content may be used in multiple campaigns.  **I STRONGLY want to move away from what i see as a big limiter to our future of campaign-message and content-unit's being the same**
* *content-group*:   filter, curated list of content-unit
* *campaign/message*:   targeting, scheduling, presentation:   refers to either content-unit or content-group.   even if 20 campaigns use same content-unit, only 1 content-unit exists.  I really do NOT want to have a campaign-message with variations where we learn a title works better, but can't be applied to the content-unit because it was part of a not-re-useable campaign.  Ie, we learned title2 works better but can't be applied to blog because was only learned for a home-page promotion widget.

**Comment by markhayden** [comment]
> Im not sure i want to merge/conflate/combine what i see as 2 concepts

agree with that. not sure if the intent or any of the ideas were specific to altering variations. IF we support that i agree it would be done with content collections far outside of pathfora likely. so lets definitely focus purely on `content recommendation` (pulling in recommended pieces of content, 1 or many for a specific user)

> specific to pathfora

i feel like this ticket is starting to be more of a "future of content" discussion rather than a very specific "demonstrate content recommendations in pathfora" discussion

> to keep moving forward lets have this iteration of pathfora include specifically

1. new template to handle displaying a content recommendation (title, description, image, url) on existing widget types (message, form, gate).
2. very very simple filters to apply to the recommendation (e.g. i want to recommend blog content)
3. ability to pull in recommended content from existing api for an individual, not for a segment

so something, high level like this:

```
var promoWidget = new pathfora.Message({
  "layout": "modal",
  "variation": 3,
  "msg": "some cool content we know you'll be interested in",
  "ref": [
    {
      "title": "My Page Title",
      "descr": "My page meta description",
      "img": "http://mypageimage.com/woot.jpg",
      "url": "http://google.com",
      "type": "recommendation"
    }
  ]
});
```

where all data in `ref` is what is being returned from our existing content api

**Comment by markhayden** [comment]
closing and simplifying to prevent confusion
